#!/home/jack/miniconda3/envs/deep/bin/python
# -*- coding: utf-8 -*-
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
import logging
import bson

# Uncomment the following line to enable verbose logging
# logging.basicConfig(level=logging.INFO)

# Create a new ChatBot instance
bot = ChatBot('Botman',
    storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
    logic_adapters=['chatterbot.logic.BestMatch'],
    filters=['chatterbot.filters.RepetitiveResponseFilter'],
    input_adapter='chatterbot.input.TerminalAdapter',
    output_adapter='chatterbot.output.TerminalAdapter',
    database_uri='mongodb://localhost:27017/chatterbot3-database'
)
trainer = ChatterBotCorpusTrainer(bot)


trainer.train("chatterbot.corpus.english")
trainer.train("./father.corpus.json")
trainer.train("./export2.json")
#trainer.train("./exportAll.json")
trainer.train("./aaajson.json")
trainer.train("./aabjson.json")
trainer.train("./aacjson.json")
trainer.train("./aadjson.json")
trainer.train("./aaejson.json")
trainer.train("./aafjson.json")
trainer.train("./aagjson.json")
trainer.train("./aahjson.json")
trainer.train("./aaijson.json")
trainer.train("./aajjson.json")
trainer.train("./aakjson.json")
trainer.train("./aaljson.json")
trainer.train("./aamjson.json")
trainer.train("./aanjson.json")
trainer.train("./aaoCjson.json")
trainer.train("./aaojson.json")
trainer.train("./aapjson.json")
trainer.train("./aaqCjson.json")
trainer.train("./aaqjson.json")
trainer.train("./aarjson.json")
trainer.train("./aasjson.json")
trainer.train("./aatjson.json")
trainer.train("./aaujson.json")
trainer.train("./aavjson.json")
trainer.train("./aawjson.json")
trainer.train("./aaxjson.json")


#bot.trainer.export_for_training('GIGANTIC.json')



print('Type something to begin...')

while True:
    try:
        user_input = input()
        if user_input=="quit":
            break
        bot_response = bot.get_response(user_input)

        print(bot_response)

    # Press ctrl-c or ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break
#chatbot.get_response("Hello, how are you today?")